# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCWQmD_qRAhaHWX0f5_cT-EgzkRIitMG
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Fungsi untuk membuat dataframe
def create_pollutant_mean_df(df, df_name, pollutant):
    df_name = df.groupby(by='station').agg({pollutant:'mean'}).sort_values(by=pollutant, ascending=False).reset_index()
    df_name.rename(columns={
    'station':'Distrik',
    pollutant:'Rata-Rata Konsentrasi'
    }, inplace=True)

    return df_name

def create_pollutant_all_df(df):
    pollutant_all_df = all_df[['TEMP', 'PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']]
    pollutant_all_df.rename(columns={
    'TEMP':'Temperatur'
    }, inplace=True)

    return pollutant_all_df

# Pembuatan DataFrame

url = 'https://raw.githubusercontent.com/krisawahyukurniawan/analisis-data-dicoding/main/dataset'
all_df = pd.read_csv(url)

pollutant_mean_dfs = {
    'PM2.5': create_pollutant_mean_df(all_df, 'pollutant_pm25', 'PM2.5'),
    'PM10': create_pollutant_mean_df(all_df, 'pollutant_pm10', 'PM10'),
    'SO2': create_pollutant_mean_df(all_df, 'pollutant_so2', 'SO2'),
    'NO2': create_pollutant_mean_df(all_df, 'pollutant_no2', 'NO2'),
    'CO': create_pollutant_mean_df(all_df, 'pollutant_co', 'CO'),
    'O3': create_pollutant_mean_df(all_df, 'pollutant_o3', 'O3')
}
pollutant_all_df = create_pollutant_all_df(all_df)

# Antarmuka Dashboard
st.title('Proyek Analisis Data: Air Quality')
st.caption("Krisa Wahyu Kurniawan | krisawahyukurniawan@gmail.com")

st.header('Gambaran')
st.write('Dataset yang digunakan pada dashboard ini adalah dataset kualitas udara yang dapat diakses pada [tautan berikut](https://github.com/krisawahyukurniawan/analisis-data-dicoding/blob/main/dataset). Dataset ini memiliki 420.768 baris data dari dua belas dokumen CSV yang telah dibersihkan dan digabungkan. Proses pembersihan dataset dan _exploratory data analysis_ pada dataset ini dapat diakses pada [notebook berikut](https://github.com/krisawahyukurniawan/analisis-data-dicoding/blob/main/notebook.ipynb).')
st.write("Dataset kualitas udara ini memiliki tujuh belas kolom yang dapat dilihat contoh data teratasnya sebagai berikut:")
st.write(all_df.head(10))

st.header('Konsentrasi Polutan Paling Tinggi')
st.write('Dengan menggunakan visualisasi diagram batang, dapat dilihat stasiun dengan konsentrasi polutan paling tinggi. Visualisasi ini menampilkan lima stasiun teratas dengan konsentrasi polutan paling tinggi.')
tabs = st.tabs([f'Polutan {pollutant}' for pollutant in pollutant])
pollutant = ['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']
tabs = st.tabs([f'Polutan {p}' for p in pollutant])
colors = ["#408ABF", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

for i, pollutant in enumerate(pollutant):
    with tabs[i]:
        fig, ax = plt.subplots(figsize=(18, 6))
        sns.barplot(x='Rata-Rata Konsentrasi', y='Distrik', data=pollutant_mean_dfs[pollutant].head(5), palette=colors)
        ax.set_ylabel(None)
        ax.tick_params(axis='y', labelsize=15)
        ax.tick_params(axis='x', labelsize=15)
        st.pyplot(fig)


st.header('Korelasi Polutan PM2.5 dengan Polutan Lain')
st.write('Dengan menggunakan visualisasi diagram _scatter plot_, dapat dilihat keterkaitan antara polutan PM2.5 dengan polutan lain. Keterkaitan kuat terlihat antara polutan PM2.5 dengan polutan PM10 dan CO. Keterkaitan lemah terlihat antara polutan PM2.5 dengan polutan SO2, NO2, dan O3.')

fig, axs = plt.subplots(nrows=3, ncols=2, figsize=(18, 18))

for ax, pollutant in zip(axs.flat, pollutants):
    sns.scatterplot(x='PM2.5', y=pollutant, data=pollutant_all_df, ax=ax, s=10)
    ax.set_title(f"Polutan {pollutant}", loc="center", fontsize=15)

st.pyplot(fig)

